### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by theoparis** [facebookresearch/shumai#119]
Neovim, and probably vscode gives an error when importing shumai in an IDE, because there are no autogenerated type declarations from tsc.

```
Cannot find module '@shumai/shumai' or its corresponding type declarations.
```

The solution is to use tsc to only emit .d.ts files in a `dist` folder, and then to use the `types` field in package.json.

It will probably run fine but any IDE will not get autocompletion. 

By the way I am using [typescript-language-server](https://github.com/typescript-language-server/typescript-language-server) - maybe direct .ts module imports could be implemented there as well.
Edit: seems like tsserver/typescript would need to implement it on their end.

**Comment by bwasti** [comment]
just pushed the latest with type information -- should be working now!

**Comment by cryptodeal** [comment]
I'm using in an external project now and can confirm that VSCode is working is getting autocompletion/type hints as expected, so I believe we're good to mark this as closed!
