### ISSUE TITLE
Forced GC during backward optimization slows training up to 60x

### ISSUE THREAD

**Issue by asilvas** [facebookresearch/shumai#125]
https://github.com/facebookresearch/shumai/blob/main/shumai/tensor/tensor.ts#L416

`tensor.update()` invocations are very high during backward pass and these GC calls are killing performance. There are a number of directions that will greatly improve the situation but wasn't sure if you had a plan/pattern in mind.

**Comment by bwasti** [comment]
absolutely we should remove this for now. What are your thoughts on direction for improvement?  Ideally WebKit/Bun would expose a way to eagerly destroy tensors when reference counts hit zero (I believe this exists to some degree for WebAssembly memory, although I'm not sure)

**Comment by asilvas** [comment]
Not sure the most optimal path for tracking references yet. A stop gap might be to include a lower & upper bound threshold for memory usage (which can be overridden) to avoid hitting GC's in tight loops. I'd also move the check into the Tensor constructor so all code paths can benefit. Happy to contribute if you think this is worth while.

Example:

```
// tensor.ts
constructor() {
  gcAsNeeded();
}

// util/gc.ts
let delayBetweenGCs = 1000;
let nextGC = Date.now() + delayBetweenGCs;
let lowerBoundThreshold = 100e6; // 100MB
let upperBoundThreshold = 5e9; // 5GB should suffice for most devices these days

export function gcAsNeeded() {
  const bytesUsed = fl.bytesUsed.native();
  const now = Date.now();
  if ((bytesUsed >= upperBoundThreshold) || (now >= nextGC && bytesUsed >= lowerBoundThreshold) {
    Bun.gc(true);
    nextGC = now + delayBetweenGCs;
  }
}

export function setOptions(opts) {} // TODO
```

Not the most elegant solution but should be somewhat optimal. Not aware we even have a way via FL to measure available memory so we could avoid using arbitrary thresholds.

**Comment by asilvas** [comment]
Attempted to leverage `FinalizationRegistry` but did not behave as I had hoped and seems unlikely to be the right solution

**Comment by bwasti** [comment]
I think that's a good solution proposal.  Would really appreciate the contribution :)

Nit: is `performance.timeOrigin + performance.now()` preferred to `Date.now()`?  I saw mention of it in a Bun commit.

**Comment by asilvas** [comment]
We only care about relative time diff so shouldn't need `timeOrigin`.
