### ISSUE TITLE
Safe dispose

### ISSUE THREAD

**Issue by asilvas** [facebookresearch/shumai#143]
As software gets more complex there may be a mix of `tidy` usage and direct `dispose`. Is there a safe to implement this?

Happy to contribute a fix that simply checks a `isDisposed` state if that is sufficient.

**Comment by cryptodeal** [comment]
I think we can add the same check that's used in the `destroyTensor` [finalizer](https://github.com/facebookresearch/shumai/blob/main/shumai/cpp/flashlight_binding.cc#L381) to the existing `dispose` method as such, I think that would suffice:

```cc
void dispose(void* t) {
  LOCK_GUARD
  auto& tensor = *reinterpret_cast<fl::Tensor*>(t);
  if (tensor.hasAdapter()) {
    g_bytes_used -= tensor.bytes();
    fl::detail::releaseAdapterUnsafe(tensor);
  }
}
```

**Comment by asilvas-godaddy** [comment]
I'll take a stab at it this evening and get feedback

**Comment by asilvas** [comment]
I'll take a stab at it this evening and get feedback
