### ISSUE TITLE
Implement common modules

### ISSUE THREAD

**Issue by bwasti** [facebookresearch/shumai#18]
Plenty to do here, may as well create a set of well known modules so folks don't have to rewrite them.

One thing to consider is not baking this into `@shumai/shumai` but instead a different repo.

**Comment by bwasti** [comment]
Started here: https://github.com/facebookresearch/shumai/commit/d1351e69feb3b7b7317ada9acf64cb2dfc514238

**Comment by cryptodeal** [comment]
> Plenty to do here, may as well create a set of well known modules so folks don't have to rewrite them.
> 
> One thing to consider is not baking this into `@shumai/shumai` but instead a different repo.

Once Bun adds support for monorepos, it'd be really easy to break the codebase into intuitive sub-packages; Case in point, Tensorflow.js is broken into packages, e.g. `@tensorflow/tfjs`, `@tensorflow/tfjs-layers`, `@tensorflow/tfjs-data`, `@tensorflow/tfjs-vis`, etc.
