### ISSUE TITLE
Error handling from C++

### ISSUE THREAD

**Issue by bwasti** [facebookresearch/shumai#26]
A formal notion of operation failure should exist at the C ABI level.  This likely entail returning nullptr or error codes from every method.

**Comment by cryptodeal** [comment]
@bwasti reached out in the FFI channel on Discord RE this and per Jarred, there are 5 bits that we might use to tag the `ptr` value returned with an error code value.

Digging through Bun's codebase, this seems the most relevant to how Bun FFI tags pointers at present, which provides some insight into how such an approach to error handling from C++ might take shape: https://github.com/oven-sh/bun/blob/0c2a207d82f42caa1d1f360c5ed56c92443c4795/src/bun.js/api/FFI.h

**Comment by cryptodeal** [comment]
After thinking about trying to find a simpler solution for comprehensive error handling, I think the simplest approach (that would make it easy to implement custom backends), would be to just print the error from native code and return `nullptr`; this would mean that anytime JS receives a `nullptr`, we can immediately throw an error with stack trace (except for those cases where there's an implemented fallback we'll want to try first).

But this would seem best of both worlds in that it removes the added complexity/limitations of tagging pointers with error codes and should provide all the same benefits in that we'll get comprehensive error info from native code + stack trace from JS with insight into where the native Fn throwing the error was called.

**Comment by cryptodeal** [comment]
I think we might be able to close this. 💯
