### ISSUE TITLE
Request for `Tensor.dispose`

### ISSUE THREAD

**Issue by asilvas** [facebookresearch/shumai#50]
Currently working around this by dereferencing tensor objects and calling `Bun.gc(true)` but this hasn't been reliable. I don't see any way currently to force the release of tensors, synchronously or otherwise.

Optionally this pattern could be useful as well: https://js.tensorflow.org/api/latest/#tidy

**Comment by bwasti** [comment]
this is very reasonable and I think it will require using Bun's `deallocatorContext` version of `toArrayBuffer` (passing information about whether a manual `dispose` was already called to prevent a double free)

**Comment by cryptodeal** [comment]
Working on implementing this now!

**Comment by bwasti** [comment]
@cryptodeal implemented all of these APIs :)
