### ISSUE TITLE
Request for `Tensor::type`

### ISSUE THREAD

**Issue by asilvas** [facebookresearch/shumai#51]
Not sure if changing the [data type](https://github.com/flashlight/flashlight/blob/main/flashlight/fl/tensor/Types.h#L15-L28) of tensors is on your radar yet.

**Comment by bwasti** [comment]
definitely on the radar, but not on the critical path yet.  Shouldn't be too hard to implement since we basically just wrap Flashlight's type stuff, but there's a fair amount to audit.

I think the first thing to get working is support for int64 tensors (for indexing)

**Comment by bwasti** [comment]
with the landing of PR's #55 and #57 , I think we're all set!  thanks @cryptodeal for taking on this issue :)

some usage examples can be found here: https://github.com/facebookresearch/shumai/blob/main/test/dtype.test.ts#L7-L16
