### ISSUE TITLE
Missing linux arm64 bindings

### ISSUE THREAD

**Issue by neo773** [facebookresearch/shumai#53]
Hi,

I'm trying to run this on a linux arm64 machine but the bindings seem to be missing for it.
```
error: Cannot find package "@shumai/linux_arm64_shumai_flashlight/libflashlight_binding.so" from "/home/opc/benchmarks/node_modules/@shumai/shumai/shumai/ffi/ffi_flashlight.ts"
```

**Comment by bwasti** [comment]
@jacobkahn does GH have runners? I think we could add this pretty easily, no?

**Comment by jacobkahn** [comment]
Super easy to add, but Github doesn't have self runners for Linux ARM. I'll look into cross compiling.

**Comment by theo-m** [comment]
Hey I'm interested in trying the lib and helping if I can - if this is a low prio for your team I could look into it

**Comment by bwasti** [comment]
hey @theo-m, thanks for the reach out!  The reason for the lag on this is that arrayfire doesn't ship arm64 binaries for linux (`libarrayfire-cpu3` is woefully out of date).

If you're interested, we would need a build script for arrayfire (from source) + fl bindings with that build.  Basically a replacement for these lines: https://github.com/facebookresearch/shumai/blob/main/.github/workflows/build.yml#L160-L166

Ideally some kind of `install_arrayfire_linux_arm64.sh` that we can use to create binaries with :)

**Comment by neo773** [comment]
@bwasti Have you looked at [BuildJet](https://buildjet.com/for-github-actions)? seems like a drop in replacement for GitHub actions and it supports Linux on arm64.

**Comment by bwasti** [comment]
alright I've got an initial pass working -- but there are some workarounds required...

- first you'll have to run this script (builds and installs arrayfire):

```bash
curl -L -O https://raw.githubusercontent.com/facebookresearch/shumai/main/.github/scripts/install_arrayfire-shumai-flashlight-linux-arm64-cpu.sh
bash install_arrayfire-shumai-flashlight-linux-arm64-cpu.sh
```

- second you'll have to install the CPU backend (and manually rename it to not CPU)

```bash
bun add @shumai/linux_arm64_shumai_flashlight_cpu
mv node_modules/@shumai/linux_arm64_shumai_flashlight_cpu node_modules/@shumai/linux_arm64_shumai_flashlight
```

ideally we'd also check the cpu folders
