### ISSUE TITLE
Add Support for `Float16Array` 

### ISSUE THREAD

**Issue by cryptodeal** [facebookresearch/shumai#54]
While working on implementing Tensor Data Types, pretty quickly realized JS `TypedArray` doesn't implement `Float16Array`. Some research into solutions revealed that there's an existing library, @petamoriken/float16, that exports `Float16Array` that's been actively developed since ~2014 and has recently added support for Bun. [@petamoriken/float16 Github Repo](https://github.com/petamoriken/float16)

Seems to support Node runtimes (Bun included) as well as browser implementations (seems like the lib was created as they needed a `Float16Array` when working with WebGL).

**Comment by bwasti** [comment]
a couple points I think are worth highlighting:

- This would be the first and only required dependency not maintained by us (besides bun)
- We can support fp16 training in FL without this, just can't expose the fp16 to javascript

That being said I'm open to it! however, if would could somehow keep it optional (maybe a runtime check?), that'd be ideal.

**Comment by cryptodeal** [comment]
Yea, we would need to run some tests against say `Float32Array` in supported environments to determine the performance impact as well.

**Comment by cryptodeal** [comment]
Okay, ran some basic performance tests; constructing a `New Float16Array` is slower than `New Float32Array` when running the following test:

```ts
import { Float16Array } from '@petamoriken/float16'
const base_t0 = performance.now() / 1e3
const length = 10000
for (let i = 0; i < length; ++i) {
  const a = new Float32Array(new Array(length).map(() => Math.random()))
}
const base_t1 = performance.now() / 1e3
console.log(base_t1 - base_t0, 'seconds for Float32Array')

const float16_t0 = performance.now() / 1e3
for (let i = 0; i < length; ++i) {
  const a = new Float16Array(new Array(length).map(() => Math.random()))
}
const float16_t1 = performance.now() / 1e3
console.log(float16_t1 - float16_t0, 'seconds for Float16Array')
```

The logged results:
```sh
2.948937458 seconds for Float32Array
3.746664 seconds for Float16Array
```

However, there's a LARGE performance impact when iterating through the `Float16Array` and updating values at each index when compared to `Float32Array` in the following test:

```ts
import { Float16Array } from '@petamoriken/float16'
const base_t0 = performance.now() / 1e3
const length = 10000
for (let i = 0; i < length; ++i) {
  const a = new Float32Array(new Array(length).map(() => Math.random()))
  for (let j = 0; j < length; ++j) {
    a[j] += 1
  }
}
const base_t1 = performance.now() / 1e3
console.log(base_t1 - base_t0, 'seconds for Float32Array')

const float16_t0 = performance.now() / 1e3
for (let i = 0; i < length; ++i) {
  const a = new Float16Array(new Array(length).map(() => Math.random()))
  for (let j = 0; j < length; ++j) {
    a[j] += 1
  }
}
const float16_t1 = performance.now() / 1e3
console.log(float16_t1 - float16_t0, 'seconds for Float16Array')
```

The logged results:
```sh
2.9601393750000002 seconds for Float32Array
37.094228209 seconds for Float16Array
```

Running the same test a 2nd time yields the same results:
```sh
2.985006292 seconds for Float32Array
37.305949208 seconds for Float16Array
```

So I would say it's safe to assume that this is definitely not a viable solution as that's a HUGE performance hit here.

**Comment by asilvas** [comment]
Don't see much value in faking fp16 in js land. Should be able to create a Float16Array that is simply an alias to Float32Array for the purpose of inferring f16 to native, and for typing.

**Comment by cryptodeal** [comment]
That's probably the best call; I'd just seen it supported Bun and was curious whether it might work without a performance hit, but that's clearly not the case haha.
