### ISSUE TITLE
clang-format requirements unclear

### ISSUE THREAD

**Issue by asilvas** [facebookresearch/shumai#82]
I've tried versions 8, 10 (default for `apt-get install clang-format`), and 12 and all fail running `clang-format` via `scripts/gen_all_binding.sh`. OS: `Linux 5.15 Ubuntu 20.04.1 LTS (Focal Fossa)`

```
YAML:8:30: error: invalid boolean
AlignConsecutiveAssignments: None
                             ^~~~
Error reading /shumai/.clang-format: Invalid argument
```

I don't mind creating a PR but wasn't clear to me how others aren't having issues with this step.

**Comment by cryptodeal** [comment]
> I've tried versions 8, 10 (default for `apt-get install clang-format`), and 12 and all fail running `clang-format` via `scripts/gen_all_binding.sh`. OS: `Linux 5.15 Ubuntu 20.04.1 LTS (Focal Fossa)`
> 
> 
> 
> ```
> 
> YAML:8:30: error: invalid boolean
> 
> AlignConsecutiveAssignments: None
> 
>                              ^~~~
> 
> Error reading /shumai/.clang-format: Invalid argument
> 
> ```
> 
> 
> 
> I don't mind creating a PR but wasn't clear to me how others aren't having issues with this step.

No issues on OSx with clang-format v14.0.6 (what was default when installing via brew), so maybe it's min version 14?

**Comment by asilvas** [comment]
Thanks. This did the trick.

```
apt-get install -y clang-format-15
ln -s /usr/bin/clang-format-15 /usr/bin/clang-format
```

**Comment by cryptodeal** [comment]
Given there's not info regarding required version of clang-format and the default version installed via `apt-get` isn't sufficient to meet Shumai's requirements, I've PR'd to add the min required version of `clang-format` to `CONTRIBUTING.md`.
