### ISSUE TITLE
`valueOf()` boolean Tensors causes bun to crash

### ISSUE THREAD

**Issue by yushiyangk** [facebookresearch/shumai#86]
Minimal example:

```
const s = sm.scalar(7).isinf()
console.log(s.dtype, s.shape)
console.log(s.valueOf())
```

Output is as follows:
```
3 []

uh-oh: A C++ exception occurred
bun will crash now 😭😭😭

----- bun meta -----
Bun v0.1.13 (55bdf268) macOS Silicon 21.6.0
AutoCommand: 
Elapsed: 91ms | User: 84ms | Sys: 14ms
RSS: 84.13MB | Peak: 84.13MB | Commit: 67.11MB | Faults: 0
----- bun meta -----

Crash report saved to:
  ~/.bun/.bun-crash/v0.1.13-1666604912355.crash

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

libc++abi: terminate_handler unexpectedly returned
```

**Comment by yushiyangk** [comment]
`valueOf()` calls `toFloat32()`, which crashes on a boolean Tensor:

```
const s = sm.scalar(7).isinf()
console.log(s.dtype, s.shape)
console.log(s.toFloat32Array())
console.log(s.toFloat32())
```

gives

```
3 []
Float32Array(1) [ 0 ]

uh-oh: A C++ exception occurred
bun will crash now 😭😭😭

----- bun meta -----
Bun v0.1.13 (55bdf268) macOS Silicon 21.6.0
AutoCommand: 
Elapsed: 90ms | User: 81ms | Sys: 15ms
RSS: 81.79MB | Peak: 81.79MB | Commit: 67.11MB | Faults: 0
----- bun meta -----

Crash report saved to:
  ~/.bun/.bun-crash/v0.1.13-1666605010108.crash

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord

libc++abi: terminate_handler unexpectedly returned
```

**Comment by cryptodeal** [comment]
> `valueOf()` calls `toFloat32()`, which crashes on a boolean Tensor:
> 
> 
> 
> ```
> 
> const s = sm.scalar(7).isinf()
> 
> console.log(s.dtype, s.shape)
> 
> console.log(s.toFloat32Array())
> 
> console.log(s.toFloat32())
> 
> ```
> 
> 
> 
> gives
> 
> 
> 
> ```
> 
> 3 []
> 
> Float32Array(1) [ 0 ]
> 
> 
> 
> uh-oh: A C++ exception occurred
> 
> bun will crash now 😭😭😭
> 
> 
> 
> ----- bun meta -----
> 
> Bun v0.1.13 (55bdf268) macOS Silicon 21.6.0
> 
> AutoCommand: 
> 
> Elapsed: 90ms | User: 81ms | Sys: 15ms
> 
> RSS: 81.79MB | Peak: 81.79MB | Commit: 67.11MB | Faults: 0
> 
> ----- bun meta -----
> 
> 
> 
> Crash report saved to:
> 
>   ~/.bun/.bun-crash/v0.1.13-1666605010108.crash
> 
> 
> 
> Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord
> 
> 
> 
> libc++abi: terminate_handler unexpectedly returned
> 
> ```
> 
> 
> 
> 

Good catch! I can PR to update the logic for `valueOf` to automatically handle based on `dtype`.
